### ISSUE TITLE
Add non-labs contribution guidelines to CONTRIBUTING.md

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#196]
Thanks for the suggestion @ssun098!

**Comment by MaxWofford** [comment]
@jonleung How does this differ from labs contribution guidelines?

**Comment by jonleung** [comment]
@ssun098, I believe that you were taking lead on this issue?

Could you respond to @MaxWofford's comment?

Thanks!

**Comment by ssun098** [comment]
@MaxWofford Since everything is more "involved" for labs, I think it would be a good idea to keep labs separate from nonlabs, for the purpose of organization.  It'll only get annoying to search for a lab school vs a nonlab school if they're all compiled in the same case study folder.

Also, it's not very clear on what nonlabs programs should be doing - writing up a guideline can never hurt.  

@jonleung I'll try to get this done asap (within the next week).  Sorry for all the delay!

**Comment by jonleung** [comment]
@ssun098, no worries! I can't think of anything better than doing the same thing as labs right now (e.g. writing case studies). Totally up for ideas though!

**Comment by ssun098** [comment]
@jonleung After the contribution guidelines are written up, we really need to stress contributing though.  I feel like the interactions with nonlabs group is not good at the moment, and even though it's way more hands off than labs, there still should be some sort of communication going.

**Comment by jonleung** [comment]
@ssun098 in your opinion, what kind of interactions do you would be ideal?

**Comment by ssun098** [comment]
@jonleung Weekly checkups would be sufficient, honestly. It's pretty important to maintain some communication between hackEDU+nonlabs clubs, otherwise people will feel uncomfortable if they're getting "ignored." 

Personally I don't really notice it because I'm cool with asking you guys for help if necessary, but for those who may not know the administrative team as well, it's weird/awkward if they're not getting attention, if that makes sense at all?

**Comment by jonleung** [comment]
@ssun098 yeah! Got it thanks! @saescapa any feedback from your end?

**Comment by ssun098** [comment]
@jonleung are there nonlabs club leaders who haven't interacted too much with you or @hellyeah who would be willing to give some insight onto this issue?

**Comment by ssun098** [comment]
Also @MaxWofford totally forgot to mention this after seeing your edit, but `any others that choose to participate` is a bad precedent, in my opinion. It's like, "You guys don't really have to contribute if you don't want to!" However, contribution is VERY helpful especially from different perspectives and although it isn't required, it should be stressed/recommended.  Is that enough clarification...?

**Comment by saescapa** [comment]
So some stuff:

For the guidelines, your guidelines mentions to use c9 workspace which I supposed all the club-labs were supposed to create, but nonlabs clubs don't have it. Some small guidelines for the nonlabs would be very helpful just to make sure we don't miss anything important that labs are currently doing for case studies.

About having labs and nonlabs separated, I don't think it's a big issue. The point of this is to gather all possible events and learn from them, and my guess having the labs program is to assure the selected clubs is to provide those every week, which are very helpful. 

I agree with @ssun about clubs not being completely connected to hackEDU, I think maybe having them at least write once a week or contributing will bond the organization to the clubs.

I hope it makes sense.

**Comment by ssun098** [comment]
Thanks @saescapa!
@jonleung, was the c9 workspace created the one in the actual workshops, or something else requested?

**Comment by zachlatta** [comment]
I created #242 to track creating a guide on setting up Cloud9 workspaces for contribution.

I like changing our contribution wording to something along the lines of what @ssun098 wrote. @ssun098: want to submit a pull request to make those?

Let's hold off on putting non-labs case studies into their own directories. It's pretty easy to distinguish the difference between labs and non-labs clubs on our end because we have a list in our main spreadsheet.

I'm going to go ahead and close this issue because there doesn't seem to be anything actionable outside of #242 and @ssun098 submitting a pull request with the wording changes. If there's other stuff that should be done to address this issue, please open up a new issue that's actionable.

**Comment by MaxWofford** [comment]
> Writing up a separate guideline for people who aren't labs should make contribution a lot clearer

@ssun098 Thanks!
