### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by TheThirdOne** [hackedu/hackedu#260]
Currently this is under full default copyright. 

Creative Commons is probably the most applicable.

**Comment by paked** [comment]
I agree. :+1: for CC or a derivative.

note: for anyone not used to licensing, I always point people towards __this__ website http://choosealicense.com/, it has very good descriptions on all the licensing things

**Comment by MaxWofford** [comment]
Thoughts on Attribution-NonCommercial 4.0 International vs Attribution 4.0 International?

/cc @zachlatta @jonleung

**Comment by TheThirdOne** [comment]
I would think ShareAlike should be in there.

**Comment by ad510** [comment]
Be careful with the noncommercial licenses because they might disallow uses you probably want to allow, such as people posting workshop content on their ad-supported blogs. Also Creative Commons [doesn't recommend](https://wiki.creativecommons.org/wiki/Frequently_Asked_Questions#Can_I_use_a_Creative_Commons_license_for_software.3F) using their licenses for software for various reasons, so if you want to use them then it's probably better to say something like the code is MIT-licensed and the rest of the workshop is CC-licensed.

You may also want to consider CC0 which is essentially worldwide public domain, which I've been using for recent projects. [Here's](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F) how to apply it to software, though it's probably overkill to put the no-warranty notice in every file and putting the notice in the readme should be good enough.

**Comment by TheThirdOne** [comment]
@ad510 

I don't think there will ever be any code in this repo.

I would also support non NonCommercial.

**Comment by ad510** [comment]
@TheThirdOne What about the code snippets in the workshops?

**Comment by zachlatta** [comment]
I think I'm going to go with the Creative Commons Attribution-ShareAlike 4.0 International for content and the MIT license for code.
