### ISSUE TITLE
Pull Requesting to hackedu issue

### ISSUE THREAD

**Issue by saescapa** [hackedu/hackedu#261]
When pulling a Pull Request, commits show a range of previous commits that were already requested in previous PRs. Here is a test PR example: #259 
"Merge remote-tracking branch 'hackedu/master' " was not commited by me and it includes 42 changes from previous PRs I made and some other people.
'Test commit please ignore' was done by me.

@MaxWofford

**Comment by MaxWofford** [comment]
@saescapa I just cloned your fork down and tested everything out. It was caused by a step we forgot to document.

Here's the fix for future reference:

These instructions assume you've  set up `git add remote upstream https://github.com/hackedu/hackedu`

When you are on a branch and you want to submit a PR to `origin/master`, make sure to
1. checkout your local `master` with `git checkout master`
2. fast-forward with `git pull upstream master --rebase` to update your master branch to the upstream
3. `git checkout  my-feature-branch`
4. `git pull upstream master --rebase`, to update your feature-branch to the upstream

@zachlatta: For reference, this merge commit was caused by @saescapa needing to merge before submitting a PR, and using `git checkout feature-branch && git merge origin/master`

**Comment by saescapa** [comment]
When doing Step 2 I get `error: unknown option `rebase'`

**Comment by MaxWofford** [comment]
@saescapa Sorry that didn't work! Would you please paste the following line into the terminal: `git status && git remote -v && git pull upstream master --rebase`, then paste it here?

**Comment by saescapa** [comment]
Here is what I get:

```
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
origin	https://github.com/saescapa/hackedu/ (fetch)
origin	https://github.com/saescapa/hackedu/ (push)
fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by MaxWofford** [comment]
@saescapa Try `git add remote upstream https://github.com/hackedu/hackedu` before the other commands

**Comment by saescapa** [comment]
Error: `fatal: pathspec 'remote' did not match any files`

**Comment by MaxWofford** [comment]
@saescapa Sorry, I screwed up: `git remote add upstream https://github.com/hackedu/hackedu`

**Comment by saescapa** [comment]
Thank you @MaxWofford, all Fixed! Closed.

**Comment by MaxWofford** [comment]
Sure thing!

**Comment by paked** [comment]
Should a note on this be added somewhere in the repository?
