### ISSUE TITLE
Prototype curriculum / general portal

### ISSUE THREAD

**Issue by jonleung** [hackedu/hackedu#421]
@paked let's work on a hackEDU / curriculum portal this week that lets everyone find everything they need related to hackEDU!

**Comment by paked** [comment]
@jonleung lets do it!

**Comment by zachlatta** [comment]
Notes from the planning call this morning:

- This will be a plain Markdown file (so no website or anything like that)
- Links to each workshop
- Links to icebreakers
- Links to Packrat
- Links to Slack
- Links to Facebook group
- Other things of the above variety

**Comment by zachlatta** [comment]
Alright, I've submitted #468 to address this. Couple notes about the pull request:

- I didn't link to icebreakers because I couldn't find any in this repo
- I didn't link to Packrat because we aren't necessarily using it at every meeting right now
- I didn't link to the Facebook group because it's invite-only and those already in it can get to it from the homepage of Facebook

**Comment by MaxWofford** [comment]
I think it would be beneficial to add packrat. A few club leaders have had trouble finding it in the past, and some clubs are still using it.

**Comment by zachlatta** [comment]
Where do you think would be the best place to add it?

**Comment by MaxWofford** [comment]
@zachlatta Not sure. On second though, it might not be a huge value add.

**Comment by zachlatta** [comment]
What if we proceed as is for now (unless @jonleung thinks this should be added now) and then add a link to Packrat later if it comes up again?
