### ISSUE TITLE
Create Messenger group chat for Labs leaders

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#72]
Thoughts on also buying IRCCloud accounts for all of the Labs leaders so they can also be in our main team chat? They're only $5/month.

#48 and #55 need to be done before this can be.

**Comment by hellyeah** [comment]
@zachlatta I want to do anything that increases the bandwidth for communication between Labs Directors. If you think IRC could do so, I think it's a no-brainer to do this.

Additionally, it may be worth considering Slack instead of Messenger, but my intuition tells me that a Messenger Group Chat is the most likely way we can get these leaders actively communicating. 

Lastly, we may want to have Labs Directors do a call every week, but at the least we should have them do an initial call together ASAP. We should probably let them coordinate this amongst themselves.

**Comment by hellyeah** [comment]
We should definitely figure out how we want to do this so we can get these group chats going by end of day today at least for the first cohort.

**Comment by zachlatta** [comment]
Agreed. We'll have an opportunity to chat about this during lunch.

I've also opened #99 to track setting up an initial call between all of the
Labs Team. Thoughts on how to go about coordinating that (or how to get
them to coordinate it amongst themselves)? Can you actually add discussing
this to today's lunch agenda?

On Thu, Aug 27, 2015 at 8:21 AM, David Fontenot <notifications@github.com>
wrote:

> We should definitely figure out how we want to do this so we can get these
> group chats going by end of day today at least for the first cohort.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/hackedu/issues/72#issuecomment-135467067>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
#111 and #113 replace this.
