### ISSUE TITLE
Accept cohort 2 of labs

### ISSUE THREAD

**Issue by zachlatta** [hackedu/hackedu#94]
Accept the leaders for the second cohort of the Labs Team.

**Comment by hellyeah** [comment]
Just finished accepting all of cohort 2: https://docs.google.com/spreadsheets/d/1Q6E36NK7N_mKp_LJwMW-P3KUZXPsHQTJWyoyKvrneuc/edit#gid=652345821

Note: Accepted Amy via Messenger bc she's out of the country.

**Comment by zachlatta** [comment]
Awesome! Closing this.

**Comment by hellyeah** [comment]
confused why this didnt get the red closed thingymabob on the zenhub board

**Comment by MaxWofford** [comment]
@hellyeah Sometimes ZenHub derps and takes time to update. The important part is that the issue says it is closed, because ZenHub will straighten itself in a few hours.

![screenshot 2015-08-27 at 11 08 26 am](https://cloud.githubusercontent.com/assets/5891442/9528888/f65e5670-4cab-11e5-8376-bea205dca162.png)
